### ISSUE TITLE
could you add installation instructions for the plugin?

### ISSUE THREAD

**Issue by PerfectCarl** [gregorej/vala-intellij-plugin#37]
I would like to test the plugin but I'm fairly new to idea. 

Could you help me to install the plugin?

**Comment by gregorej** [comment]
You can just download one of the releases (https://github.com/gregorej/vala-intellij-plugin/releases), then Intellij -> File -> Settings -> (search for Plugins) -> Plugins -> Install from disk.

**Comment by PerfectCarl** [comment]
Yes, that's perfect.

Thanks.
