### ISSUE TITLE
could you add a quick list of features?

### ISSUE THREAD

**Issue by PerfectCarl** [gregorej/vala-intellij-plugin#38]
Thanks for your work on this plugin.

Could you add a quick doc section detailing the supported ones, the planned ones...

It would make following the project a lot easier.

**Comment by gregorej** [comment]
Thanks for the heads up!

I am going to add a proper change log with following release (should be coming soon). About planned features you can just browse through issues with label feature or take a look at milestones

**Comment by PerfectCarl** [comment]
Thanks!
