### ISSUE TITLE
Just a thought ;)

### ISSUE THREAD

**Issue by activey** [gregorej/vala-intellij-plugin#45]
Hi there,

Have you considered using jni to call some vala library that will do most of those parsing and stuff related for you?

**Comment by gregorej** [comment]
That would probably fall into #36. But I do not think it would use JNI, rather some Intellij mechanism to call external tools.

**Comment by activey** [comment]
I was rather thinking of preparing set of native vala/c libraries that will support your intellij extension, valac binary is nice but it could be more valuable when you rewrite it and use it as a some kind of information provider, you could also use it to provide a list of system vapis, etc, etc.

But sure, it was just a proposal ;)

**Comment by gregorej** [comment]
If you would like to prepare such a thing, feel free. Could we chat about it on https://gitter.im/gregorej/vala-intellij-plugin? I will close this issue for now

**Comment by activey** [comment]
Gitter requires my company resources access, no way ;)
